/**
 * Mock data adapter. This is the ONLY place that fabricates data.
 * When the real Node.js + MySQL REST API is available, delete this file and
 * point `src/lib/api.ts` at the HTTP client (see TODO markers there).
 */
import bearingImg from "@/assets/part-bearing.jpg";
import valveImg from "@/assets/part-valve.jpg";
import turbineImg from "@/assets/part-turbine.jpg";
import pumpImg from "@/assets/part-pump.jpg";
import electricalImg from "@/assets/part-electrical.jpg";
import sealImg from "@/assets/part-seal.jpg";
import type {
  Brand,
  Category,
  Manufacturer,
  NotificationItem,
  Order,
  Product,
  Seller,
  SellerListing,
  SettlementRecord,
} from "./types";

export const IMAGES = {
  bearing: bearingImg,
  valve: valveImg,
  turbine: turbineImg,
  pump: pumpImg,
  electrical: electricalImg,
  seal: sealImg,
};

const CATEGORY_SEED: [string, string[]][] = [
  ["Turbine Components", ["Runners & Buckets", "Guide Vanes", "Shafts", "Wear Rings"]],
  ["Generator Components", ["Rotor Parts", "Stator Parts", "Excitation", "Slip Rings"]],
  ["Bearings", ["Ball Bearings", "Roller Bearings", "Thrust Bearings", "Bushings"]],
  ["Valves", ["Butterfly Valves", "Gate Valves", "Relief Valves", "Check Valves"]],
  ["Pumps", ["Centrifugal Pumps", "Dosing Pumps", "Pump Spares"]],
  ["Hydraulic Components", ["Cylinders", "Hoses & Fittings", "Hydraulic Pumps", "Accumulators"]],
  ["Electrical Components", ["Relays", "Circuit Breakers", "Cables", "Transformers"]],
  ["Control & Instrumentation", ["Sensors", "PLC Modules", "Transmitters", "Governors"]],
  ["Seals & Gaskets", ["Shaft Seals", "O-Rings", "Gasket Sheets"]],
  ["Fasteners", ["Bolts & Nuts", "Studs", "Washers"]],
  ["Couplings", ["Flexible Couplings", "Rigid Couplings"]],
  ["Pipes & Fittings", ["Penstock Fittings", "Flanges", "Elbows"]],
  ["Lubrication", ["Greases", "Oils", "Lubrication Units"]],
  ["Cooling Components", ["Heat Exchangers", "Cooling Fans", "Radiators"]],
  ["Mechanical Components", ["Gearboxes", "Belts & Chains", "Shaft Keys"]],
  ["Other Hydropower Spare Parts", ["Trash Rack Parts", "Gate Parts", "Misc"]],
];

const slugify = (s: string) =>
  s
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");

let catId = 0;
export const categories: Category[] = CATEGORY_SEED.map(([name, subs], i) => {
  const parent: Category = {
    id: ++catId,
    parentId: null,
    name,
    slug: slugify(name),
    sortOrder: i + 1,
    status: "ACTIVE",
    children: [],
  };
  parent.children = subs.map((sub, j) => ({
    id: ++catId + 1000,
    parentId: parent.id,
    name: sub,
    slug: slugify(sub),
    sortOrder: j + 1,
    status: "ACTIVE" as const,
  }));
  return parent;
});

export const brands: Brand[] = [
  "Andritz",
  "Voith",
  "SKF",
  "Siemens",
  "Parker",
  "Danfoss",
  "Grundfos",
  "Trelleborg",
].map((n, i) => ({ id: i + 1, name: n, slug: slugify(n) }));

export const manufacturers: Manufacturer[] = ([
  ["Andritz Hydro", "Austria"],
  ["Voith Hydro", "Germany"],
  ["SKF Group", "Sweden"],
  ["Siemens Energy", "Germany"],
  ["Kirloskar", "India"],
  ["Nepal Hydro & Electric", "Nepal"],
] as [string, string][]).map(([n, c], i) => ({ id: i + 1, name: n, slug: slugify(n), country: c }));

export const sellers: Seller[] = [
  {
    id: 1,
    userId: 11,
    businessName: "Himalaya Hydro Traders",
    businessType: "Private Limited",
    registrationNumber: "REG-104928",
    panNumber: "601234567",
    vatNumber: "601234567",
    description: "Supplier of turbine and generator spares for Nepali hydropower plants since 2009.",
    address: "Balaju Industrial District",
    province: "Bagmati",
    district: "Kathmandu",
    city: "Kathmandu",
    approvalStatus: "APPROVED",
    commissionRate: 8,
    rating: 4.7,
    totalProducts: 128,
    createdAt: "2024-02-11T04:00:00Z",
  },
  {
    id: 2,
    userId: 12,
    businessName: "Gandaki Power Spares",
    businessType: "Partnership",
    registrationNumber: "REG-220145",
    panNumber: "607781234",
    description: "Bearings, seals and mechanical components distributor based in Pokhara.",
    address: "Newroad, Pokhara-9",
    province: "Gandaki",
    district: "Kaski",
    city: "Pokhara",
    approvalStatus: "APPROVED",
    commissionRate: 10,
    rating: 4.4,
    totalProducts: 76,
    createdAt: "2024-06-02T04:00:00Z",
  },
  {
    id: 3,
    userId: 13,
    businessName: "Koshi Electromech Supply",
    businessType: "Sole Proprietorship",
    registrationNumber: "REG-338790",
    panNumber: "609912345",
    description: "Electrical, control and instrumentation spares for small hydro projects.",
    address: "Dharan Road",
    province: "Koshi",
    district: "Sunsari",
    city: "Itahari",
    approvalStatus: "APPROVED",
    commissionRate: 9,
    rating: 4.2,
    totalProducts: 54,
    createdAt: "2025-01-19T04:00:00Z",
  },
  {
    id: 4,
    userId: 14,
    businessName: "Lumbini Industrial Hardware",
    businessType: "Private Limited",
    registrationNumber: "REG-410233",
    panNumber: "602277881",
    description: "Fasteners, pipes and fittings wholesaler.",
    address: "Butwal Industrial Area",
    province: "Lumbini",
    district: "Rupandehi",
    city: "Butwal",
    approvalStatus: "PENDING",
    commissionRate: 10,
    rating: 0,
    totalProducts: 0,
    createdAt: "2026-07-28T04:00:00Z",
  },
  {
    id: 5,
    userId: 15,
    businessName: "Karnali Machine Works",
    businessType: "Partnership",
    registrationNumber: "REG-509911",
    panNumber: "604411223",
    description: "Machining workshop offering refurbished turbine components.",
    address: "Surkhet Road",
    province: "Karnali",
    district: "Surkhet",
    city: "Birendranagar",
    approvalStatus: "PENDING",
    commissionRate: 12,
    rating: 0,
    totalProducts: 0,
    createdAt: "2026-08-14T04:00:00Z",
  },
];

interface Seed {
  name: string;
  cat: number;
  sub: number;
  part: string;
  oem: string;
  brand: number;
  man: number;
  img: string;
  price: number;
  short: string;
  specs: Record<string, string>;
  compat: string[];
}

const SEEDS: Seed[] = [
  {
    name: "Pelton Runner Bucket Segment 320 mm",
    cat: 1,
    sub: 0,
    part: "HS-TRB-320",
    oem: "AH-PLT-320-04",
    brand: 1,
    man: 1,
    img: "turbine",
    price: 184500,
    short: "CA6NM stainless steel bucket segment for Pelton runners up to 3 MW.",
    specs: {
      Material: "CA6NM Stainless Steel",
      "Bucket Width": "320 mm",
      Hardness: "280-320 HB",
      Finish: "Machined & polished",
      Weight: "18.4 kg",
    },
    compat: ["Pelton 2-jet 1.5 MW", "Pelton 4-jet 3 MW", "NHE-P320 series"],
  },
  {
    name: "Francis Guide Vane Bush Set",
    cat: 1,
    sub: 1,
    part: "HS-GVB-118",
    oem: "VH-GV-118",
    brand: 2,
    man: 2,
    img: "turbine",
    price: 62400,
    short: "Self-lubricating guide vane bushes, set of 6, for Francis units.",
    specs: { Material: "Bronze / PTFE", "Inner Dia": "118 mm", "Set Size": "6 pcs" },
    compat: ["Francis 1.2 MW", "Francis 5 MW"],
  },
  {
    name: "Turbine Main Shaft Sleeve 210 mm",
    cat: 1,
    sub: 2,
    part: "HS-SHS-210",
    oem: "AH-SL-210",
    brand: 1,
    man: 6,
    img: "turbine",
    price: 96800,
    short: "Hard-chromed shaft sleeve for main turbine shafts.",
    specs: { Material: "SS 420 hard chrome", Length: "410 mm", "Bore Dia": "210 mm" },
    compat: ["Francis 5 MW", "Kaplan 8 MW"],
  },
  {
    name: "Deep Groove Ball Bearing 6205-2RS",
    cat: 3,
    sub: 0,
    part: "6205-2RS",
    oem: "SKF-6205-2RS1",
    brand: 3,
    man: 3,
    img: "bearing",
    price: 1500,
    short: "Sealed deep groove ball bearing, 25x52x15 mm, for auxiliary drives.",
    specs: { Bore: "25 mm", "Outer Dia": "52 mm", Width: "15 mm", "Max Speed": "14000 rpm" },
    compat: ["Auxiliary pump units", "Cooling fan assemblies"],
  },
  {
    name: "Spherical Roller Bearing 22320 E",
    cat: 3,
    sub: 1,
    part: "22320-E",
    oem: "SKF-22320E",
    brand: 3,
    man: 3,
    img: "bearing",
    price: 42800,
    short: "Heavy duty spherical roller bearing for generator shaft support.",
    specs: { Bore: "100 mm", "Outer Dia": "215 mm", Width: "73 mm", "Dynamic Load": "610 kN" },
    compat: ["Generator 3 MW", "Gearbox HS-GB4"],
  },
  {
    name: "Thrust Bearing Pad Set — 12 Segments",
    cat: 3,
    sub: 2,
    part: "HS-TBP-12",
    oem: "VH-TB-12S",
    brand: 2,
    man: 2,
    img: "bearing",
    price: 268000,
    short: "Babbitt-lined thrust pads for vertical generator units.",
    specs: { Segments: "12", Lining: "Tin-based babbitt", "Pad Dia": "180 mm" },
    compat: ["Vertical Francis 10 MW"],
  },
  {
    name: "Butterfly Valve DN400 PN16 with Actuator",
    cat: 4,
    sub: 0,
    part: "HS-BV-400",
    oem: "DF-BV400-PN16",
    brand: 6,
    man: 4,
    img: "valve",
    price: 315000,
    short: "Main inlet butterfly valve with electric actuator and limit switches.",
    specs: {
      "Nominal Dia": "DN400",
      Pressure: "PN16",
      Body: "Ductile Iron GGG40",
      Actuator: "230 V AC electric",
    },
    compat: ["Penstock DN400 lines"],
  },
  {
    name: "Pressure Relief Valve 2 inch",
    cat: 4,
    sub: 2,
    part: "HS-PRV-050",
    oem: "PK-PRV-2IN",
    brand: 5,
    man: 5,
    img: "valve",
    price: 24500,
    short: "Adjustable relief valve for hydraulic governor circuits.",
    specs: { Size: "2 in", "Set Range": "20-160 bar", Body: "Carbon steel" },
    compat: ["Governor hydraulic unit HPU-2"],
  },
  {
    name: "Centrifugal Cooling Water Pump 7.5 kW",
    cat: 5,
    sub: 0,
    part: "HS-CWP-75",
    oem: "GR-NK-7.5",
    brand: 7,
    man: 5,
    img: "pump",
    price: 148000,
    short: "End-suction cooling water pump for bearing and generator cooling loops.",
    specs: { Power: "7.5 kW", Flow: "60 m3/h", Head: "32 m", Voltage: "400 V 3-ph" },
    compat: ["Cooling loop CL-2", "Bearing cooling skid"],
  },
  {
    name: "Pump Mechanical Seal Kit 45 mm",
    cat: 9,
    sub: 0,
    part: "HS-MSK-045",
    oem: "TB-MS-45",
    brand: 8,
    man: 3,
    img: "seal",
    price: 8900,
    short: "Cartridge mechanical seal kit with SiC faces and Viton elastomers.",
    specs: { "Shaft Dia": "45 mm", Faces: "SiC / Carbon", Elastomer: "Viton" },
    compat: ["HS-CWP-75", "Dosing pump DP-1"],
  },
  {
    name: "Shaft Oil Seal 120x150x12",
    cat: 9,
    sub: 0,
    part: "HS-OS-120150",
    oem: "TB-OS-120150",
    brand: 8,
    man: 3,
    img: "seal",
    price: 2650,
    short: "Nitrile rotary shaft seal for gearbox and bearing housings.",
    specs: { "Inner Dia": "120 mm", "Outer Dia": "150 mm", Width: "12 mm", Material: "NBR" },
    compat: ["Gearbox HS-GB4", "Bearing housing BH-120"],
  },
  {
    name: "Overcurrent Protection Relay 3-Phase",
    cat: 7,
    sub: 0,
    part: "HS-OCR-3P",
    oem: "SE-7SR11",
    brand: 4,
    man: 4,
    img: "electrical",
    price: 76500,
    short: "Numerical overcurrent and earth fault relay for generator protection.",
    specs: { Phases: "3", "Aux Supply": "24-240 V", Protocol: "Modbus RTU", Mounting: "Panel" },
    compat: ["Generator protection panel GP-2"],
  },
  {
    name: "Speed Sensor / Pickup Module",
    cat: 8,
    sub: 0,
    part: "HS-SPD-01",
    oem: "SE-SP-1001",
    brand: 4,
    man: 4,
    img: "electrical",
    price: 18700,
    short: "Magnetic pickup speed sensor for turbine governor feedback.",
    specs: { Output: "Sine wave", "Thread Size": "M16x1.5", "Cable Length": "3 m" },
    compat: ["Governor GOV-3", "Speed monitor SM-2"],
  },
  {
    name: "Hydraulic Cylinder 80/45 x 400 Stroke",
    cat: 6,
    sub: 0,
    part: "HS-HC-8045",
    oem: "PK-HC-8045-400",
    brand: 5,
    man: 5,
    img: "pump",
    price: 132000,
    short: "Double-acting hydraulic cylinder for guide vane servo operation.",
    specs: { Bore: "80 mm", "Rod Dia": "45 mm", Stroke: "400 mm", Pressure: "210 bar" },
    compat: ["Guide vane servo GVS-1"],
  },
];

export const products: Product[] = SEEDS.map((s, i) => {
  const cat = categories[s.cat]!;
  const sub = cat.children?.[s.sub] ?? null;
  const imgUrl = IMAGES[s.img as keyof typeof IMAGES];
  return {
    id: i + 1,
    categoryId: cat.id,
    subcategoryId: sub ? sub.id : null,
    brandId: s.brand,
    manufacturerId: s.man,
    name: s.name,
    slug: slugify(s.name),
    sku: `SKU-${1000 + i}`,
    partNumber: s.part,
    oemNumber: s.oem,
    productCode: `HS-${2000 + i}`,
    shortDescription: s.short,
    description: `${s.short} Supplied through Hydro Sathi verified sellers with full traceability of part number and OEM reference. Every unit is inspected before dispatch and comes with the seller's standard warranty for hydropower plant applications in Nepal.`,
    material: s.specs["Material"] ?? s.specs["Body"] ?? "Steel",
    weightKg: 2 + i,
    specifications: s.specs,
    compatibility: s.compat,
    images: [
      { id: i * 3 + 1, productId: i + 1, imageUrl: imgUrl, altText: s.name, sortOrder: 1, isPrimary: true },
      {
        id: i * 3 + 2,
        productId: i + 1,
        imageUrl: IMAGES[(["turbine", "bearing", "valve", "pump", "electrical", "seal"] as const)[i % 6]!],
        altText: `${s.name} alternate view`,
        sortOrder: 2,
        isPrimary: false,
      },
      {
        id: i * 3 + 3,
        productId: i + 1,
        imageUrl: IMAGES[(["seal", "pump", "electrical", "turbine", "valve", "bearing"] as const)[i % 6]!],
        altText: `${s.name} detail view`,
        sortOrder: 3,
        isPrimary: false,
      },
    ],
    status: i === SEEDS.length - 1 ? "PENDING_REVIEW" : "ACTIVE",
    createdAt: new Date(2026, 1 + (i % 6), 3 + i).toISOString(),
  };
});

export const listings: SellerListing[] = products.flatMap((p, i) => {
  const base = SEEDS[i]!.price;
  const sellerIds = [1, 2, 3];
  const count = (i % 3) + 1;
  return Array.from({ length: count }, (_, k) => {
    const sellerId = sellerIds[(i + k) % 3]!;
    const factor = 1 + (k === 0 ? 0 : k * 0.06) - (k === 1 ? 0.1 : 0);
    return {
      id: p.id * 10 + k,
      productId: p.id,
      sellerId,
      sellerSku: `S${sellerId}-${p.sku}`,
      price: Math.round(base * factor),
      compareAtPrice: Math.round(base * 1.15),
      stockQuantity: [12, 4, 0, 25, 7][(i + k) % 5]!,
      minimumOrderQuantity: 1,
      condition: (k === 2 ? "REFURBISHED" : "NEW") as SellerListing["condition"],
      leadTimeDays: 3 + ((i + k) % 7),
      status: "ACTIVE" as const,
      approvalStatus: (p.status === "PENDING_REVIEW" ? "PENDING_REVIEW" : "APPROVED") as SellerListing["approvalStatus"],
      createdAt: p.createdAt,
    };
  });
});

export const orders: Order[] = [
  {
    id: 1,
    orderNumber: "HS-2026-000141",
    userId: 1,
    buyerName: "Sunkoshi Power Pvt. Ltd.",
    items: [
      {
        id: 1,
        productId: 4,
        listingId: 40,
        sellerId: 2,
        productNameSnapshot: "Deep Groove Ball Bearing 6205-2RS",
        partNumberSnapshot: "6205-2RS",
        sellerNameSnapshot: "Gandaki Power Spares",
        quantity: 10,
        unitPrice: 1500,
        subtotal: 15000,
        commissionRate: 10,
        commissionAmount: 1500,
        sellerAmount: 13500,
      },
      {
        id: 2,
        productId: 10,
        listingId: 100,
        sellerId: 1,
        productNameSnapshot: "Pump Mechanical Seal Kit 45 mm",
        partNumberSnapshot: "HS-MSK-045",
        sellerNameSnapshot: "Himalaya Hydro Traders",
        quantity: 2,
        unitPrice: 8900,
        subtotal: 17800,
        commissionRate: 8,
        commissionAmount: 1424,
        sellerAmount: 16376,
      },
    ],
    shippingAddress: {
      fullName: "Ram Bahadur Thapa",
      phone: "+977 9801234567",
      addressLine1: "Sunkoshi Powerhouse, Site Office",
      province: "Bagmati",
      district: "Sindhupalchok",
      city: "Barhabise",
    },
    subtotal: 32800,
    deliveryCharge: 1200,
    taxAmount: 4264,
    discountAmount: 0,
    commissionAmount: 2924,
    totalAmount: 38264,
    currency: "NPR",
    paymentProvider: "ESEWA",
    paymentStatus: "PAID",
    orderStatus: "SHIPPED",
    trackingNumber: "NPX-778213",
    courierName: "Nepal Can Move",
    createdAt: "2026-08-12T05:20:00Z",
    history: [
      { status: "PAYMENT_CONFIRMED", at: "2026-08-12T05:22:00Z", note: "eSewa txn verified server-side" },
      { status: "SELLER_CONFIRMED", at: "2026-08-12T09:10:00Z" },
      { status: "ADMIN_APPROVAL", at: "2026-08-13T04:00:00Z" },
      { status: "READY_FOR_SHIPPING", at: "2026-08-13T06:30:00Z" },
      { status: "SHIPPED", at: "2026-08-14T03:15:00Z", note: "Dispatched via Nepal Can Move" },
    ],
  },
  {
    id: 2,
    orderNumber: "HS-2026-000158",
    userId: 1,
    buyerName: "Sunkoshi Power Pvt. Ltd.",
    items: [
      {
        id: 3,
        productId: 7,
        listingId: 70,
        sellerId: 1,
        productNameSnapshot: "Butterfly Valve DN400 PN16 with Actuator",
        partNumberSnapshot: "HS-BV-400",
        sellerNameSnapshot: "Himalaya Hydro Traders",
        quantity: 1,
        unitPrice: 315000,
        subtotal: 315000,
        commissionRate: 8,
        commissionAmount: 25200,
        sellerAmount: 289800,
      },
    ],
    shippingAddress: {
      fullName: "Ram Bahadur Thapa",
      phone: "+977 9801234567",
      addressLine1: "Sunkoshi Powerhouse, Site Office",
      province: "Bagmati",
      district: "Sindhupalchok",
      city: "Barhabise",
    },
    subtotal: 315000,
    deliveryCharge: 3500,
    taxAmount: 40950,
    discountAmount: 5000,
    commissionAmount: 25200,
    totalAmount: 354450,
    currency: "NPR",
    paymentProvider: "KHALTI",
    paymentStatus: "PAID",
    orderStatus: "SELLER_PENDING_CONFIRMATION",
    createdAt: "2026-08-20T08:40:00Z",
    history: [{ status: "PAYMENT_CONFIRMED", at: "2026-08-20T08:42:00Z", note: "Khalti lookup verified" }],
  },
  {
    id: 3,
    orderNumber: "HS-2026-000162",
    userId: 2,
    buyerName: "Marsyangdi Hydro Ltd.",
    items: [
      {
        id: 4,
        productId: 12,
        listingId: 120,
        sellerId: 3,
        productNameSnapshot: "Overcurrent Protection Relay 3-Phase",
        partNumberSnapshot: "HS-OCR-3P",
        sellerNameSnapshot: "Koshi Electromech Supply",
        quantity: 2,
        unitPrice: 76500,
        subtotal: 153000,
        commissionRate: 9,
        commissionAmount: 13770,
        sellerAmount: 139230,
      },
    ],
    shippingAddress: {
      fullName: "Sita Gurung",
      phone: "+977 9845001122",
      addressLine1: "Marsyangdi Corridor, Plant Store",
      province: "Gandaki",
      district: "Lamjung",
      city: "Besisahar",
    },
    subtotal: 153000,
    deliveryCharge: 2000,
    taxAmount: 19890,
    discountAmount: 0,
    commissionAmount: 13770,
    totalAmount: 174890,
    currency: "NPR",
    paymentProvider: "COD",
    paymentStatus: "PENDING",
    orderStatus: "PAYMENT_CONFIRMED",
    createdAt: "2026-08-22T10:05:00Z",
    history: [{ status: "PAYMENT_CONFIRMED", at: "2026-08-22T10:06:00Z", note: "COD approved by admin" }],
  },
];

export const settlements: SettlementRecord[] = [
  {
    id: 1,
    sellerId: 1,
    orderNumber: "HS-2026-000141",
    grossAmount: 17800,
    commissionAmount: 1424,
    refundAmount: 0,
    netAmount: 16376,
    status: "PENDING",
    createdAt: "2026-08-14T03:15:00Z",
  },
  {
    id: 2,
    sellerId: 1,
    orderNumber: "HS-2026-000158",
    grossAmount: 315000,
    commissionAmount: 25200,
    refundAmount: 0,
    netAmount: 289800,
    status: "ON_HOLD",
    createdAt: "2026-08-20T08:42:00Z",
  },
  {
    id: 3,
    sellerId: 1,
    orderNumber: "HS-2026-000119",
    grossAmount: 92000,
    commissionAmount: 7360,
    refundAmount: 2000,
    netAmount: 82640,
    status: "PAID",
    createdAt: "2026-07-30T08:42:00Z",
  },
];

export const notifications: NotificationItem[] = [
  {
    id: 1,
    type: "SELLER_REGISTRATION",
    title: "New seller application",
    message: "Karnali Machine Works submitted registration documents.",
    isRead: false,
    createdAt: "2026-08-22T09:00:00Z",
  },
  {
    id: 2,
    type: "ORDER_PAID",
    title: "New paid order HS-2026-000158",
    message: "Khalti payment verified. Awaiting seller confirmation.",
    isRead: false,
    createdAt: "2026-08-20T08:42:00Z",
  },
  {
    id: 3,
    type: "PRODUCT_SUBMITTED",
    title: "Product pending review",
    message: "Hydraulic Cylinder 80/45 x 400 Stroke awaits approval.",
    isRead: true,
    createdAt: "2026-08-18T06:10:00Z",
  },
];
